# Generated by Django 4.2.6 on 2023-10-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_events_end_events_start_alter_events_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
