# Generated by Django 4.2.6 on 2023-11-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_events_end_events_start_alter_events_table'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='events',
    #         name='start',
    #     ),
    # ]
