# Generated by Django 4.2.6 on 2023-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_remove_events_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
