# Generated by Django 4.2.6 on 2023-10-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_rename_end_date_events_expiration_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.CharField(default='재료', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='expiration_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
