# Generated by Django 4.2.6 on 2023-10-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_events_categories_alter_events_expiration_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='events',
            name='expiration_dt',
        ),
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
