# Generated by Django 4.2.6 on 2023-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='f_categories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
