# Generated by Django 4.2.6 on 2023-11-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_events_f_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='f_categories',
            new_name='f_category',
        ),
    ]
