# Generated by Django 4.2.6 on 2023-10-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_remove_events_categories_remove_events_expiration_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
    ]
