# Generated by Django 4.2.6 on 2023-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0008_rename_end_events_expiration_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.CharField(blank=True, default='재료', max_length=255, null=True),
        ),
    ]
