# Generated by Django 4.2.6 on 2023-10-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_events_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='expiration_dt',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='categories',
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
