# Generated by Django 4.2.6 on 2023-11-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_rename_expiration_dt_events_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(blank=True, choices=[('food', '재료'), ('no-food', '비재료')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(default='입력 필요', max_length=255),
        ),
    ]
