# Generated by Django 4.2.6 on 2023-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0014_alter_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('food', '재료'), ('no-food', '비재료'), ('none', '선택하지 않음')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
