# Generated by Django 4.2.6 on 2023-11-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0016_alter_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
    ]
